CREATE SCHEMA IF NOT EXISTS  `ustfits` ;

CREATE TABLE `ustfits`.`accounts` (
  `USERNAME` VARCHAR(45) NOT NULL,
  `PASSWORD` VARCHAR(45) NOT NULL,
  `ROLE` VARCHAR(45) NOT NULL,
  `RESETPIN` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`USERNAME`),
  UNIQUE INDEX `USERNAME_UNIQUE` (`USERNAME` ASC),
  UNIQUE INDEX `PASSWORD_UNIQUE` (`PASSWORD` ASC),
  UNIQUE INDEX `RESETPIN_UNIQUE` (`RESETPIN` ASC));

  
  CREATE TABLE IF NOT EXISTS `ustfits`.`studententrylog` (
  `SN` INT,
  `NAME` VARCHAR(45) NOT NULL,
  `ENTRYTYPE` VARCHAR(45) NOT NULL,
  `TIMESTAMP` VARCHAR(45) NOT NULL);
  
  CREATE TABLE IF NOT EXISTS  `ustfits`.`studentexitlog` (
  `SN` INT,
  `NAME` VARCHAR(45) NOT NULL,
  `ENTRYTYPE` VARCHAR(45) NOT NULL,
  `EQUIPMENTS` VARCHAR(45) NOT NULL);
  
  CREATE TABLE IF NOT EXISTS `ustfits`.`sslog` (
  `NAME` VARCHAR(45) NOT NULL,
  `TIMESTAMP` VARCHAR(45) NOT NULL,
  `EDIT_HISTORY` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`NAME`));
    
CREATE TABLE IF NOT EXISTS `ustfits`.`adminlog` (
  `NAME` VARCHAR(45) NOT NULL,
  `TIMESTAMP` VARCHAR(45) NOT NULL,
  `EDIT_HISTORY` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`NAME`));
  
  
  CREATE TABLE IF NOT EXISTS `ustfits`.`equipments` (
  `NAME` VARCHAR(45) NOT NULL,
  `DESCRIPTION` VARCHAR(45) NOT NULL,
  `QUANTITY` INT NOT NULL,
  `PICTURE` BLOB NOT NULL,
  PRIMARY KEY (`NAME`));
  
  CREATE TABLE IF NOT EXISTS `ustfits`.`trainers` (
  `NAME` VARCHAR(45) NOT NULL,
  `SPECIALITY` VARCHAR(45) NOT NULL,
  `SPORT` VARCHAR(45) NOT NULL,
  `PICTURE` BLOB NOT NULL,
  PRIMARY KEY (`NAME`));
  

