CREATE SCHEMA IF NOT EXISTS  `ustfits` ;

CREATE TABLE `ustfits`.`accounts` (
  `USERNAME` VARCHAR(45) NOT NULL,
  `PASSWORD` VARCHAR(45) NOT NULL,
  `ROLE` VARCHAR(45) NOT NULL,
  `RESETPIN` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`USERNAME`),
  UNIQUE INDEX `USERNAME_UNIQUE` (`USERNAME` ASC),
  UNIQUE INDEX `PASSWORD_UNIQUE` (`PASSWORD` ASC),
  UNIQUE INDEX `RESETPIN_UNIQUE` (`RESETPIN` ASC));

  
  CREATE TABLE IF NOT EXISTS `ustfits`.`studententrylog` (
  `SN` INT NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  `ENTRYTYPE` VARCHAR(45) NOT NULL,
  `TIMESTAMP` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`SN`));
  
  CREATE TABLE IF NOT EXISTS  `ustfits`.`studentexitlog` (
  `SN` INT NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  `ENTRYTYPE` VARCHAR(45) NOT NULL,
  `EQUIPMENTS_USED` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`SN`));
  
  CREATE TABLE IF NOT EXISTS `ustfits`.`sslog` (
  `NAME` VARCHAR(45) NOT NULL,
  `TIMESTAMP` VARCHAR(45) NOT NULL,
  `EDIT_HISTORY` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`NAME`));
  
CREATE TABLE IF NOT EXISTS `ustfits`.`adminlog` (
  `NAME` VARCHAR(45) NOT NULL,
  `TIMESTAMP` VARCHAR(45) NOT NULL,
  `EDIT_HISTORY` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`NAME`));

